AllCops:
  Exclude:
    - 'bin/**/*'
    - '*.gemspec'
  DisplayCopNames: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Metrics/LineLength:
  Max: 100
